GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/6057c581fa380805d59a1c74

###

DELETE http://localhost:3001/api/persons/6057c581fa380805d59a1c74

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Viktoria Stepanenko",
    "number": 1
}
